root = "."
tmp_dir = "tmp"

[build]
# Build both WASM and backend
cmd = "make build-wasm && go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["dist", "tmp", "vendor"]
include_dir = []
exclude_file = ["frontend/internal/version.go"]
delay = 1000
stop_on_error = true
log = "air_errors.log"
send_interrupt = true
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 